// <auto-generated />
using System;
using Entidades.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Programa.Migrations
{
    [DbContext(typeof(PracticeContext))]
    [Migration("20231130022558_NewChanges")]
    partial class NewChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entidades.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTrabajo")
                        .IsUnique();

                    b.ToTable("personas");
                });

            modelBuilder.Entity("Entidades.Models.Trabajo", b =>
                {
                    b.Property<int>("IdTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrabajo"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTrabajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrabajoIdTrabajo")
                        .HasColumnType("int");

                    b.HasKey("IdTrabajo");

                    b.HasIndex("TrabajoIdTrabajo");

                    b.ToTable("trabajos");
                });

            modelBuilder.Entity("Entidades.Models.Persona", b =>
                {
                    b.HasOne("Entidades.Models.Trabajo", "Trabajo")
                        .WithOne("Persona")
                        .HasForeignKey("Entidades.Models.Persona", "IdTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Entidades.Models.Trabajo", b =>
                {
                    b.HasOne("Entidades.Models.Trabajo", null)
                        .WithMany("trabajos")
                        .HasForeignKey("TrabajoIdTrabajo");
                });

            modelBuilder.Entity("Entidades.Models.Trabajo", b =>
                {
                    b.Navigation("Persona")
                        .IsRequired();

                    b.Navigation("trabajos");
                });
#pragma warning restore 612, 618
        }
    }
}
